import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useParams, Link, Navigate } from 'react-router-dom';
import { useLanguage } from '@/contexts/LanguageContext';
import { Button } from '@/components/ui/button';
import { ArrowLeft, ChevronLeft, ChevronRight, ImageIcon, Play } from 'lucide-react';
import { 
  servicePricing, 
  getLocalizedText,
  type ServicePricing,
} from '@/data/pricing';
import { Dialog, DialogContent } from '@/components/ui/dialog';

type MediaType = 'image' | 'video' | 'unknown';

const VIDEO_EXTS = new Set(['mp4', 'webm', 'mov']);
const IMAGE_EXTS = new Set(['jpg', 'jpeg', 'png', 'webp']);

const getMediaTypeFromPath = (src: string): MediaType => {
  // Strip query/hash to get a clean file extension.
  const clean = src.split('#')[0]?.split('?')[0] ?? src;
  const lastDot = clean.lastIndexOf('.');
  if (lastDot === -1) return 'unknown';
  const ext = clean.slice(lastDot + 1).toLowerCase();
  if (VIDEO_EXTS.has(ext)) return 'video';
  if (IMAGE_EXTS.has(ext)) return 'image';
  return 'unknown';
};

/**
 * Map URL slugs to service IDs.
 * This allows for URL-friendly paths like /gallery/face-painting
 */
const slugToServiceId: Record<string, string> = {
  characters: 'characters',
  balloons: 'balloon',
  entertainers: 'entertainers',
  'face-painting': 'facePainting',
  shows: 'shows',
  'special-characters': 'mobileSpa',
  // Legacy alias for backwards compatibility; handled via redirect below.
  'mobile-spa': 'mobileSpa',
};

/**
 * Gallery manifest lives in `public/gallery-manifest.json` and is generated by
 * `scripts/build-gallery-manifest.js` (run automatically via npm pre-scripts).
 */
const placeholderCount = 6;

type GalleryManifest = {
  version: number;
  generatedAt: string;
  categories: Record<string, string[]>;
};

const Gallery = () => {
  const { category } = useParams<{ category: string }>();
  const { t, language } = useLanguage();

  const [lightboxOpen, setLightboxOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  const [manifest, setManifest] = useState<GalleryManifest | null>(null);
  const [manifestError, setManifestError] = useState<string | null>(null);
  const videoRef = useRef<HTMLVideoElement | null>(null);

  const normalizedCategory = useMemo(() => {
    if (!category) return undefined;
    const lower = category.toLowerCase();
    if (lower === 'mobile-spa') return 'special-characters';
    if (lower === 'facepainting') return 'face-painting';
    if (lower === 'special') return 'special-characters';
    if (lower === 'specialcharacters') return 'special-characters';
    return lower;
  }, [category]);

  // Redirect to canonical slug variants (case differences + legacy aliases)
  if (category && normalizedCategory && category !== normalizedCategory) {
    return <Navigate to={`/gallery/${normalizedCategory}`} replace />;
  }

  // Convert URL slug to service ID
  const serviceId = normalizedCategory ? slugToServiceId[normalizedCategory] : undefined;
  
  // Find the service data
  const service: ServicePricing | undefined = serviceId 
    ? servicePricing.find((s) => s.id === serviceId)
    : undefined;

  // If category doesn't exist, redirect to pricing
  if (!service) {
    return <Navigate to="/pricing" replace />;
  }

  const serviceName = getLocalizedText(service.name, language);

  const baseUrl = import.meta.env.BASE_URL || '/';
  const manifestUrl = useMemo(() => {
    const normalizedBase = baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;
    return `${normalizedBase}gallery-manifest.json`;
  }, [baseUrl]);

  useEffect(() => {
    let cancelled = false;
    const controller = new AbortController();

    const load = async () => {
      setManifestError(null);
      try {
        const res = await fetch(manifestUrl, { signal: controller.signal });
        if (!res.ok) throw new Error(`Failed to load gallery manifest (${res.status})`);
        const json = (await res.json()) as GalleryManifest;
        if (!cancelled) setManifest(json);
      } catch (err) {
        if (controller.signal.aborted) return;
        if (!cancelled) setManifestError(err instanceof Error ? err.message : 'Failed to load gallery');
      }
    };

    load();
    return () => {
      cancelled = true;
      controller.abort();
    };
  }, [manifestUrl]);

  const galleryImages = useMemo(() => {
    if (!normalizedCategory) return [];
    const items = manifest?.categories?.[normalizedCategory] ?? [];
    const normalizedBase = baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;
    // Manifest stores public-relative paths like "images/Characters/foo.jpg"
    return items.map((p) => `${normalizedBase}${p.replace(/^\/+/, '')}`);
  }, [baseUrl, manifest, normalizedCategory]);

  const activeSrc = useMemo(() => {
    if (!lightboxOpen || activeIndex === null) return null;
    return galleryImages[activeIndex] ?? null;
  }, [activeIndex, galleryImages, lightboxOpen]);

  const openLightbox = (index: number) => {
    if (!galleryImages.length) return;
    setActiveIndex(index);
    setLightboxOpen(true);
  };

  const showPrev = useCallback(() => {
    if (!galleryImages.length || activeIndex === null) return;
    setActiveIndex((current) => {
      if (current === null) return current;
      const nextIndex = (current - 1 + galleryImages.length) % galleryImages.length;
      return nextIndex;
    });
  }, [galleryImages.length, activeIndex]);

  const showNext = useCallback(() => {
    if (!galleryImages.length || activeIndex === null) return;
    setActiveIndex((current) => {
      if (current === null) return current;
      const nextIndex = (current + 1) % galleryImages.length;
      return nextIndex;
    });
  }, [galleryImages.length, activeIndex]);

  useEffect(() => {
    if (!lightboxOpen || !galleryImages.length) return;

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'ArrowLeft') {
        event.preventDefault();
        showPrev();
      } else if (event.key === 'ArrowRight') {
        event.preventDefault();
        showNext();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [lightboxOpen, galleryImages.length, showPrev, showNext]);

  // Video autoplay (with-sound -> fallback muted) + cleanup on close/switch
  useEffect(() => {
    if (!activeSrc) return;
    if (getMediaTypeFromPath(activeSrc) !== 'video') return;

    const el = videoRef.current;
    if (!el) return;

    el.currentTime = 0;
    el.muted = false;

    const tryAutoplay = async () => {
      try {
        await el.play();
      } catch {
        try {
          el.muted = true;
          await el.play();
        } catch {
          // Autoplay blocked even when muted; controls remain available for user.
        }
      }
    };

    void tryAutoplay();

    return () => {
      el.pause();
      try {
        el.currentTime = 0;
      } catch {
        // ignore
      }
    };
  }, [activeSrc]);

  // Build contact URL with service query parameter
  const bookingUrl = `/contact?service=${encodeURIComponent(serviceName)}`;

  return (
    <main className="py-16">
      {/* Page Header */}
      <section className="container mx-auto px-4 mb-12">
        {/* Back link */}
        <Link 
          to="/pricing" 
          className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary transition-colors mb-8"
        >
          <ArrowLeft size={18} />
          {t('gallery.backToPricing')}
        </Link>

        <div className="text-center max-w-3xl mx-auto">
          <h1 className="text-4xl md:text-6xl font-bold mb-4">
            <span className="text-gradient-magical">{serviceName}</span>
          </h1>
          <p className="text-lg text-muted-foreground mb-2">
            {t('gallery.title')}
          </p>
          <p className="text-xl text-muted-foreground leading-relaxed">
            {getLocalizedText(service.description, language)}
          </p>
        </div>
      </section>

      {/* Gallery Grid */}
      <section className="container mx-auto px-4 mb-16">
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4 md:gap-6">
          {galleryImages.length > 0 ? (
            galleryImages.map((src, index) => (
              <div
                key={src}
                className="relative aspect-square rounded-2xl overflow-hidden bg-muted"
                onClick={() => openLightbox(index)}
              >
                {getMediaTypeFromPath(src) === 'video' ? (
                  <>
                    <video
                      src={src}
                      muted
                      playsInline
                      preload="metadata"
                      controls={false}
                      className="w-full h-full object-cover pointer-events-none"
                    />
                    <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
                      <div className="bg-gradient-magical p-[2px] rounded-full shadow-magical">
                        <div className="h-11 w-11 rounded-full bg-background/70 backdrop-blur-sm flex items-center justify-center">
                          <Play
                            className="h-5 w-5 text-foreground fill-foreground"
                            strokeWidth={0}
                          />
                        </div>
                      </div>
                    </div>
                  </>
                ) : (
                  <img
                    src={src}
                    alt={`${serviceName} photo ${index + 1}`}
                    className="w-full h-full object-cover"
                    loading="lazy"
                  />
                )}
              </div>
            ))
          ) : (
            Array.from({ length: placeholderCount }).map((_, index) => (
                <div
                  key={index}
                  className="aspect-square bg-muted rounded-2xl flex flex-col items-center justify-center gap-3 border-2 border-dashed border-muted-foreground/20"
                >
                  <ImageIcon size={48} className="text-muted-foreground/40" />
                  <span className="text-sm text-muted-foreground/60">
                    {manifestError ? t('gallery.loadError') : t('gallery.placeholder')}
                  </span>
                </div>
              ))
          )}
        </div>
      </section>

      {/* Lightbox Modal */}
      <Dialog open={lightboxOpen} onOpenChange={setLightboxOpen}>
        {galleryImages.length > 0 && activeIndex !== null && (
          <DialogContent className="bg-transparent border-none shadow-none p-0 max-w-none w-auto">
            <div className="relative flex items-center justify-center gap-4">
              <button
                type="button"
                aria-label={t('gallery.previousImage')}
                className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-background/85 text-foreground shadow-md hover:bg-background focus:outline-none focus:ring-2 focus:ring-ring"
                onClick={showPrev}
              >
                <ChevronLeft className="h-6 w-6" />
              </button>

              <div className="bg-gradient-magical p-[2px] sm:p-[3px] rounded-[1.75rem] shadow-magical">
                <div className="bg-background rounded-[1.5rem] p-3 sm:p-4">
                  {getMediaTypeFromPath(galleryImages[activeIndex]) === 'video' ? (
                    <video
                      key={galleryImages[activeIndex]}
                      ref={videoRef}
                      src={galleryImages[activeIndex]}
                      controls
                      playsInline
                      preload="metadata"
                      className="max-h-[80vh] max-w-[90vw] w-auto object-contain rounded-2xl"
                      aria-label={serviceName}
                    />
                  ) : (
                    <img
                      src={galleryImages[activeIndex]}
                      alt={serviceName}
                      className="max-h-[80vh] max-w-[90vw] w-auto object-contain rounded-2xl"
                    />
                  )}
                </div>
              </div>

              <button
                type="button"
                aria-label={t('gallery.nextImage')}
                className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-background/85 text-foreground shadow-md hover:bg-background focus:outline-none focus:ring-2 focus:ring-ring"
                onClick={showNext}
              >
                <ChevronRight className="h-6 w-6" />
              </button>
            </div>
          </DialogContent>
        )}
      </Dialog>

      {/* Book Service CTA */}
      <section className="container mx-auto px-4">
        <div className="bg-muted/50 rounded-2xl p-8 text-center">
          <h2 className="text-2xl font-bold mb-4">
            {serviceName}
          </h2>
          <p className="text-muted-foreground mb-6 max-w-xl mx-auto">
            {service.note && getLocalizedText(service.note, language)}
          </p>
          <Button asChild variant="hero" size="lg">
            <Link to={bookingUrl}>
              {t('gallery.bookService')}
            </Link>
          </Button>
        </div>
      </section>

      {/* Decorative Elements */}
      <div className="fixed top-1/4 left-4 w-8 h-8 bg-primary/20 rounded-full animate-float" />
      <div className="fixed top-1/3 right-8 w-6 h-6 bg-secondary/20 rounded-full animate-float" style={{ animationDelay: '1s' }} />
      <div className="fixed bottom-1/4 left-8 w-4 h-4 bg-accent/30 rounded-full animate-float" style={{ animationDelay: '0.5s' }} />
    </main>
  );
};

export default Gallery;

